# Change these first
owner: enlivenonedrive # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aarohisilk
    url: https://aarohisilks.com
  - name: Arkanfoods
    url: http://raknfoods.com/
  - name: Enliven Designers
    url: https://enlivendesigners.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Vialanka Travels
    url: https://vialankatravels.com
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.enlivendesigners.com
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Enliven Designers Infrastructure Status 
  introTitle: "**Enliven Designers** Real-Time Service Health Dashboard."
  introMessage: Monitoring uptime so your creativity never stops.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
