# Change these first
owner: enlivenonedrive # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aarohisilk
    url: https://aarohisilks.com
  - name: Airtopup
    url: https://airtopup.com
  - name: Amazetrading
    url: https://amazetrading.ca
  - name: Arkanfood
    url: https://raknfoods.com
  - name: Ceylononlineshop
    url: https://ceylononlineshop.com
  - name: Cocomileceylon
    url: https://cocomillceylon.com
  - name: Contractpoints
    url: https://contractpoints.com
  - name: Dipuravana
    url: https://dipuravana.com
  - name: Dipuravanarentals
    url: https://dipuravanarentals.com
  - name: Dynamicspize
    url: https://dynamicspize.com
  - name: Econtips
    url: https://econtips.com
  - name: Ecuniversity
    url: https://ecuniversity.online
  - name: Enliven Designers
    url: https://enlivendesigners.com
  - name: Evershinecoaches
    url: https://evershinecoaches.co.uk
  - name: Fnilogistics
    url: http://fnilogistics.com
  - name: Freightnetwork
    url: https://freightnetwork.enlivendesigners.com
  - name: Gsmwholesaler
    url: https://gsmwholesaler.com
  - name: Jesuranwellness
    url: http://jesuranwellness.com
  - name: Notionblend
    url: https://notionblend.com
  - name: Owkuniversity
    url: https://owkuniversity.online
  - name: Primeserviceglobal
    url: https://primeservicesglobal.co.uk
  - name: Primeteaceylon
    url: https://primeteaceylon.com
  - name: Rbpesolutions
    url: https://rbpesolutions.co.uk
  - name: Rmylogistics
    url: https://rmylogistics.com
  - name: Seflk
    url: https://seflk.org
  - name: Startglobal
    url: https://startglobalsl.co.uk
  - name: Symbiosophy
    url: http://symbiosophy.org
  - name: Symbioun
    url: https://symbioun.lk
  - name: Symbiouncommunity
    url: https://symbiouncommunity.org
  - name: Tactsolutions
    url: https://tactsolutionslk.com
  - name: Technifyit
    url: https://technifyit.co.uk
  - name: Ukallbl
    url: https://ukallbl.institute
  - name: Ukcclqv
    url: https://ukcclqv.institute
  - name: Ukckabl
    url: https://ukckabl.institute
  - name: Unitedxchange
    url: https://unitedxchange.co.uk
  - name: Unreachedbrands
    url: https://unreachedbrands.com
  - name: Vialanka Travels
    url: https://vialankatravels.com
  - name: Staging Server
    url: 81.0.218.72
    check: "tcp-ping"
    ipv6: false
  - name: Production Server 1
    url: 194.163.168.18
    check: "tcp-ping"
    ipv6: false
  - name: Production Server 2
    url: 194.163.166.206
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.enlivendesigners.com
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Enliven Designers Infrastructure Status 
  introTitle: "**Enliven Designers** Real-Time Service Health Dashboard."
  introMessage: Monitoring uptime so your creativity never stops.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://enlivendesigners.com/
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
